name: Sync Fork with Upstream

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config user.name "siro844"
        git config user.email "srinathreddy239@gmail.com"

    - name: Add upstream repository
      run: git remote add upstream https://github.com/Archi-tech-AI/architech-landing.git

    - name: Fetch upstream
      run: git fetch upstream

    - name: Merge upstream changes
      run: git merge upstream/main

    - name: Push changes
      run: git push origin main
